# Generated by Django 5.2.1 on 2025-05-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('video_id', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('incidents_found', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
