# Generated by Django 5.2.1 on 2025-05-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
